# version: '3.8'
services:
  web:
    build:    
      context: .
      dockerfile: Dockerfile
  
    volumes:
      - static_volume:/impression-carte/PrintCard/static
    env_file:
      - .env 
    ports:
      - "8004:8004"
    environment:
      DATABASE_URL: postgres://postgres:postgres@192.168.1.252:5432/impressiondb
    networks:
      - print_network 
  nginx:
    image: nginx:latest 
    volumes:
      - static_volume:/impression-carte/PrintCard/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
    - web
    networks:
    - print_network 

volumes:  
  static_volume:
  
networks:
  print_network:
    driver: bridge
