name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build . --file Dockerfile \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/impression-carte:${GITHUB_SHA::8} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/impression-carte:latest

      - name: List Docker Images
        run: docker images

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/impression-carte:${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/impression-carte:latest

  deploy:
    needs: build
    name: Deploy Image to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy Application
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          WORK_DIR: ${{ secrets.WORK_DIR }}
        run: |
          ssh $SSH_USER@$SSH_HOST << EOF
            cd $WORK_DIR
            docker compose pull
            docker compose up -d
          EOF

      - name: Cleanup SSH Keys
        run: rm -rf ~/.ssh

    - name: Connect and Pull New Image
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d"

    - name: Cleanup SSH
      run: rm -rf ~/.ssh
  
